services:
  - type: web
    name: portfolio-app
    env: node
    buildCommand: "npm install"
    startCommand: "node server.js"
    envVars:
      - key: NODE_ENV
        value: production
    plan: free
    autoDeploy: true
    branch: main
